spring:
  data:
    rest:
      max-page-size: 100
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootJPAHikariCP
    platform: postgres
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/database/changelog-master.xml
    enabled: false
  profiles:
    active: dev
management:
  server:
    port: 8081
    address: 127.0.0.1
